//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLAzure1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoTipo
    {
        public MovimientoTipo()
        {
            this.Movimientoes = new HashSet<Movimiento>();
        }
    
        public int IdMovimientoTipo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Movimiento> Movimientoes { get; set; }
    }
}
