//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLAzure1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Aseguradoras = new HashSet<Aseguradora>();
            this.Direccions = new HashSet<Direccion>();
            this.EmpresaPolizas = new HashSet<EmpresaPoliza>();
            this.Movimientoes = new HashSet<Movimiento>();
            this.Polizas = new HashSet<Poliza>();
            this.Vigencias = new HashSet<Vigencia>();
        }
    
        public int IdUsuario { get; set; }
        public string UserName { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Curp { get; set; }
        public byte[] Imagen { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IdRol { get; set; }
    
        public virtual ICollection<Aseguradora> Aseguradoras { get; set; }
        public virtual ICollection<Direccion> Direccions { get; set; }
        public virtual ICollection<EmpresaPoliza> EmpresaPolizas { get; set; }
        public virtual ICollection<Movimiento> Movimientoes { get; set; }
        public virtual ICollection<Poliza> Polizas { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Vigencia> Vigencias { get; set; }
    }
}
