//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Dependientes = new HashSet<Dependiente>();
        }
    
        public string NumeroEmpleado { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string NSS { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdPoliza { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Dependiente> Dependientes { get; set; }
        public virtual Poliza Poliza { get; set; }
    }
}
