//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaPoliza
    {
        public int IdEmpresaPoliza { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdPoliza { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Poliza Poliza { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
