//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoDetalle
    {
        public int IdMovimientoDetalle { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
