//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vigencia
    {
        public int IdVigencia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificaion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdPoliza { get; set; }
    
        public virtual Poliza Poliza { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
