//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServicioEmpleado")]
    public interface IServicioEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Add", ReplyAction="http://tempuri.org/IServicioEmpleado/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference2.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReference2.Result Add(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Add", ReplyAction="http://tempuri.org/IServicioEmpleado/AddResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference2.Result> AddAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Update", ReplyAction="http://tempuri.org/IServicioEmpleado/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference2.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReference2.Result Update(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Update", ReplyAction="http://tempuri.org/IServicioEmpleado/UpdateResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference2.Result> UpdateAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Delete", ReplyAction="http://tempuri.org/IServicioEmpleado/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference2.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReference2.Result Delete(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/Delete", ReplyAction="http://tempuri.org/IServicioEmpleado/DeleteResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference2.Result> DeleteAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/GetById", ReplyAction="http://tempuri.org/IServicioEmpleado/GetByIdResponse")]
        PL.ServiceReference2.Result GetById(string NumeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/GetById", ReplyAction="http://tempuri.org/IServicioEmpleado/GetByIdResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference2.Result> GetByIdAsync(string NumeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/GetAll", ReplyAction="http://tempuri.org/IServicioEmpleado/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference2.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReference2.Result GetAll(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/GetAll", ReplyAction="http://tempuri.org/IServicioEmpleado/GetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference2.Result> GetAllAsync(ML.Empleado empleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleadoChannel : PL.ServiceReference2.IServicioEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleadoClient : System.ServiceModel.ClientBase<PL.ServiceReference2.IServicioEmpleado>, PL.ServiceReference2.IServicioEmpleado {
        
        public ServicioEmpleadoClient() {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.ServiceReference2.Result Add(ML.Empleado empleado) {
            return base.Channel.Add(empleado);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference2.Result> AddAsync(ML.Empleado empleado) {
            return base.Channel.AddAsync(empleado);
        }
        
        public PL.ServiceReference2.Result Update(ML.Empleado empleado) {
            return base.Channel.Update(empleado);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference2.Result> UpdateAsync(ML.Empleado empleado) {
            return base.Channel.UpdateAsync(empleado);
        }
        
        public PL.ServiceReference2.Result Delete(ML.Empleado empleado) {
            return base.Channel.Delete(empleado);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference2.Result> DeleteAsync(ML.Empleado empleado) {
            return base.Channel.DeleteAsync(empleado);
        }
        
        public PL.ServiceReference2.Result GetById(string NumeroEmpleado) {
            return base.Channel.GetById(NumeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference2.Result> GetByIdAsync(string NumeroEmpleado) {
            return base.Channel.GetByIdAsync(NumeroEmpleado);
        }
        
        public PL.ServiceReference2.Result GetAll(ML.Empleado empleado) {
            return base.Channel.GetAll(empleado);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference2.Result> GetAllAsync(ML.Empleado empleado) {
            return base.Channel.GetAllAsync(empleado);
        }
    }
}
